packages:
  - packages/*
  - "!**/test/**"
catalog:
  "@headlessui/vue": ^1.7.23
  "@hookform/resolvers": ^3.9.1
  "@radix-ui/react-checkbox": ^1.1.2
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-select": ^2.1.2
  "@radix-ui/react-slot": ^1.1.0
  "@tailwindcss/forms": ^0.5.9
  "@tailwindcss/postcss": ^4.0.6
  "@tailwindcss/vite": ^4.0.6
  "@tanstack/vue-table": ^8.21.2
  "@types/bcryptjs": ^2.4.6
  "@types/cookie-parser": ^1.4.8
  "@types/cors": ^2.8.17
  "@types/eslint__js": ^8.42.3
  "@types/express": 4.17.21
  "@types/find-root": ^1.1.4
  "@types/helmet": ^4.0.0
  "@types/jsonwebtoken": ^9.0.7
  "@types/jwt-decode": ^3.1.0
  "@types/morgan": ^1.9.9
  "@types/node": ^22.9.0
  "@types/pg": ^8.11.10
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/request-ip": ^0.0.41
  "@vitejs/plugin-react-swc": ^3.5.0
  "@vitejs/plugin-vue": ^5.2.1
  "@vue/tsconfig": ^0.7.0
  autoprefixer: ^10.4.20
  axios: ^1.7.7
  bcryptjs: ^2.4.3
  chalk: 4.1.2
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  concurrently: ^9.1.0
  cookie-parser: ^1.4.7
  cors: ^2.8.5
  dotenv: ^16.4.5
  drizzle-kit: ^0.28.0
  drizzle-orm: ^0.36.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  express: ^4.21.1
  find-root: ^1.1.0
  globals: ^15.11.0
  helmet: ^8.0.0
  inversify: ^6.0.3
  jsonwebtoken: ^9.0.2
  jwt-decode: ^4.0.0
  lucide-react: ^0.460.0
  lucide-vue: ^0.475.0
  moment: ^2.30.1
  morgan: ^1.10.0
  nodemon: ^3.1.7
  pg: ^8.13.1
  prettier: ^3.3.3
  react: ^18.3.1
  react-dom: ^18.3.1
  react-hook-form: ^7.53.2
  react-hot-toast: ^2.4.1
  react-router-dom: 6.24.0
  reflect-metadata: ^0.2.2
  request-ip: ^3.3.0
  resend: ^4.1.2
  rimraf: ^6.0.1
  tailwind-merge: ^2.5.4
  tailwindcss-animate: ^1.0.7
  ts-node: ^10.9.2
  ts-patch: ^3.2.1
  tsx: ^4.19.2
  typescript-transform-paths: ^3.5.2
  uuid: ^11.0.3
  vitest: ^2.1.5
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  winston: 2.4.6
  zod: ^3.23.8
