services:
  web:
    build:
      context: ../../packages/web
      dockerfile: ./Dockerfile
    container_name: web_ui
    env_file:
      - ./../../.env
    networks:
      - shared_network
    ports:
      - 8000:80
    volumes:
      - ../../packages/shared:/app/shared

networks:
  shared_network:
    external: true

volumes:
  shared_volume:
