/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseHuiModal: typeof import('./src/components/base-hui-modal.vue')['default']
    Button: typeof import('primevue/button')['default']
    DTable: typeof import('./src/components/d-table.vue')['default']
    DTableTBody: typeof import('./src/components/d-table-t-body.vue')['default']
    DTableTHead: typeof import('./src/components/d-table-t-head.vue')['default']
    DTableTPagination: typeof import('./src/components/d-table-t-pagination.vue')['default']
    FormPasswordInput: typeof import('./src/components/form-password-input.vue')['default']
    FormTaglist: typeof import('./src/components/form-taglist.vue')['default']
    FormTextInput: typeof import('./src/components/form-text-input.vue')['default']
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
    HmpBanner: typeof import('./src/components/hmp-banner.vue')['default']
    HmpTeam: typeof import('./src/components/hmp-team.vue')['default']
    HmpTeamMember: typeof import('./src/components/hmp-team-member.vue')['default']
    HmpWhyChoice: typeof import('./src/components/hmp-why-choice.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingComponent: typeof import('./src/components/loading-component.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModalAddDepartmentMember: typeof import('./src/components/modal-add-department-member.vue')['default']
    ModalAssignDeptRole: typeof import('./src/components/modal-assign-dept-role.vue')['default']
    ModalCreateDesignation: typeof import('./src/components/modal-create-designation.vue')['default']
    ModalCreateOrUpdateDepartment: typeof import('./src/components/modal-create-or-update-department.vue')['default']
    ModalCreateOrUpdateDepartmentTitle: typeof import('./src/components/modal-create-or-update-department-title.vue')['default']
    ModalCreateOrUpdateOrgDesignation: typeof import('./src/components/modal-create-or-update-org-designation.vue')['default']
    ModalFormCreateOrg: typeof import('./src/components/modal-form-create-org.vue')['default']
    ModalInviteUsersToOrg: typeof import('./src/components/modal-invite-users-to-org.vue')['default']
    ModalViewDepartment: typeof import('./src/components/modal-view-department.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    NavBarItem: typeof import('./src/components/nav-bar-item.vue')['default']
    OrgCreate: typeof import('./src/components/org-create.vue')['default']
    OrgDashboardHeader: typeof import('./src/components/org-dashboard-header.vue')['default']
    OrgDashboardSidebar: typeof import('./src/components/org-dashboard-sidebar.vue')['default']
    OrgDepartmentListing: typeof import('./src/components/org-department-listing.vue')['default']
    OrgDepartmentTitleListing: typeof import('./src/components/org-department-title-listing.vue')['default']
    OrgLayoutHeader: typeof import('./src/components/org-layout-header.vue')['default']
    OrgSidebarMenuItem: typeof import('./src/components/org-sidebar-menu-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('primevue/tab')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    TActionButtons: typeof import('./src/components/t-action-buttons.vue')['default']
    TheWelcome: typeof import('./src/components/the-welcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    VTable: typeof import('./src/components/v-table.vue')['default']
    WelcomeItem: typeof import('./src/components/welcome-item.vue')['default']
  }
}
