/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DTable: typeof import('./src/components/d-table/d-table.vue')['default']
    DTableTBody: typeof import('./src/components/d-table/d-table-t-body.vue')['default']
    DTableTHead: typeof import('./src/components/d-table/d-table-t-head.vue')['default']
    DTableTPagination: typeof import('./src/components/d-table/d-table-t-pagination.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormPasswordInput: typeof import('./src/components/form/form-password-input.vue')['default']
    FormTaglist: typeof import('./src/components/form/form-taglist.vue')['default']
    FormTextInput: typeof import('./src/components/form/form-text-input.vue')['default']
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
    HmpBanner: typeof import('./src/components/hmp/hmp-banner.vue')['default']
    HmpTeam: typeof import('./src/components/hmp/hmp-team.vue')['default']
    HmpTeamMember: typeof import('./src/components/hmp/hmp-team-member.vue')['default']
    HmpWhyChoice: typeof import('./src/components/hmp/hmp-why-choice.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModalCreateDesignation: typeof import('./src/components/modals/modal-create-designation.vue')['default']
    ModalCreateOrUpdateDepartment: typeof import('./src/components/modals/modal-create-or-update-department.vue')['default']
    ModalCreateOrUpdateDepartmentTitle: typeof import('./src/components/modals/modal-create-or-update-department-title.vue')['default']
    ModalCreateOrUpdateOrgDesignation: typeof import('./src/components/modals/modal-create-or-update-org-designation.vue')['default']
    ModalFormCreateOrg: typeof import('./src/components/modals/modal-form-create-org.vue')['default']
    ModalInviteUsersToOrg: typeof import('./src/components/modals/modal-invite-users-to-org.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    NavBarItem: typeof import('./src/components/nav-bar-item.vue')['default']
    OrgCreate: typeof import('./src/components/org/org-create.vue')['default']
    OrgDashboardHeader: typeof import('./src/components/org/org-dashboard-header.vue')['default']
    OrgDashboardSidebar: typeof import('./src/components/org/org-dashboard-sidebar.vue')['default']
    OrgDepartmentListing: typeof import('./src/components/org/setup/org-department-listing.vue')['default']
    OrgDepartmentTitleListing: typeof import('./src/components/org/setup/org-department-title-listing.vue')['default']
    OrgLayoutHeader: typeof import('./src/components/org/org-layout-header.vue')['default']
    OrgSidebarMenuItem: typeof import('./src/components/org/org-sidebar-menu-item.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TActionButtons: typeof import('./src/components/d-table/t-action-buttons.vue')['default']
    TheWelcome: typeof import('./src/components/the-welcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WelcomeItem: typeof import('./src/components/welcome-item.vue')['default']
  }
}
